//{{NO_DEPENDENCIES}}
// Arquivo de inclusão gerado pelo Microsoft Visual C++.
// Usado por GLPI-AgentMonitor.rc
//
#define IDC_BTN_FORCE                   101
#define IDC_BTN_NEWTICKET               102
#define IDC_BTN_CLOSE                   103
#define IDC_BTN_SETTINGS                104
#define IDI_GLPIOK                      105
#define IDR_RMENU                       141
#define IDI_GLPIERR                     148
#define IDB_LOGO                        152
#define IDD_DIALOG2                     154
#define IDD_DLG_SETTINGS                154
#define IDS_APP_TITLE                   200
#define IDS_GLPINOTIFYERROR             201
#define IDS_GLPINOTIFY                  202
#define IDS_STATIC_INFO                 203
#define IDS_STATIC_AGENTVER             204
#define IDS_STATIC_SERVICESTATUS        205
#define IDS_STATIC_STARTTYPE            206
#define IDS_ERR_AGENTSETTINGS           207
#define IDS_LOADING                     208
#define IDS_STATIC_AGENTSTATUS          209
#define IDS_FORCEINV                    210
#define IDS_CLOSE                       211
#define IDS_ERR_NOTRESPONDING           212
#define IDS_ERR_NOTRUNNING              213
#define IDS_SVCSTART_BOOT               214
#define IDS_SVCSTART_SYSTEM             215
#define IDS_SVCSTART_AUTO               216
#define IDS_SVCSTART_DELAYEDAUTO        217
#define IDS_SVCSTART_MANUAL             218
#define IDS_SVCSTART_DISABLED           219
#define IDS_ERR_UNKSVCSTART             220
#define IDS_ERR_REGFAIL                 221
#define IDS_ERR_AGENTVERNOTFOUND        222
#define IDS_ERR_AGENTNOTFOUND           223
#define IDS_ERR_HTTPDPORT               224
#define IDS_SVC_STOPPED                 225
#define IDS_SVC_RUNNING                 226
#define IDS_SVC_PAUSED                  227
#define IDS_SVC_CONTINUEPENDING         228
#define IDS_SVC_PAUSEPENDING            229
#define IDS_SVC_STARTPENDING            230
#define IDS_SVC_STOPPENDING             231
#define IDS_ERR_SERVICE                 232
#define IDS_OK                          233
#define IDS_ERROR                       234
#define IDS_ERR_FORCEINV_NORESPONSE     235
#define IDS_ERR_FORCEINV_NOTALLOWED     236
#define IDS_MSG_FORCEINV_OK             237
#define IDS_ERR_AGENTERR                238
#define IDS_RMENU_OPEN                  239
#define IDS_RMENU_FORCE                 240
#define IDS_RMENU_EXIT                  241
#define IDS_FILE                        242
#define IDS_DIR                         243
#define IDS_ERR_MAINWINDOW              244
#define IDS_RMENU_NEWTICKET             245
#define IDS_ERR_SERVER                  246
#define IDS_NOTIF_NEWTICKET_TITLE       247
#define IDS_NOTIF_NEWTICKET             248
#define IDS_NEWTICKET                   249
#define IDS_VIEWLOGS                    250
#define IDS_RMENU_VIEWLOGS              251
#define IDS_STARTSVC                    252
#define IDS_STOPSVC                     253
#define IDS_RESUMESVC                   254
#define IDS_WAIT                        255
#define IDS_ERR_SCHANDLE                256
#define IDS_ERR_SVCHANDLE               257
#define IDS_ERR_SVCOPERATION            258
#define IDS_SETTINGS                    259
#define IDS_SETTINGS_NEWTICKETURL       260
#define IDS_CHECKBOX_NEWTICKET_DEFAULTURL 261
#define IDS_ERR_SAVE_SETTINGS           261
#define IDS_CANCEL                      262
#define IDS_SAVE                        263
#define IDS_BTN_SETTINGS                264
#define IDS_RMENU_SETTINGS              265
#define IDC_BTN_VIEWLOGS                400
#define IDD_DIALOG1                     401
#define IDD_MAIN                        402
#define IDC_VERSION                     601
#define IDC_GBMAIN                      602
#define IDC_GBSTATUS                    603
#define IDC_AGENTSTATUS                 604
#define IDC_AGENTVER                    605
#define IDC_SERVICESTATUS               606
#define IDC_STARTTYPE                   607
#define IDC_PCLOGO                      609
#define IDT_UPDSTATUS                   610
#define IDT_UPDSVCSTATUS                611
#define IDC_STATIC_AGENTVER             1004
#define IDC_STATIC_SERVICESTATUS        1005
#define IDC_STATIC_STARTTYPE            1006
#define IDC_BTN_STARTSTOPSVC            1009
#define IDC_SETTINGS_EDIT_NEWTICKETURL  1010
#define IDC_CHECK1                      1011
#define IDC_CHECKBOX_NEWTICKET_DEFAULTURL 1011
#define IDC_BTN_CANCEL                  1013
#define IDC_BTN_SAVE                    1014
#define ID_RMENU_OPEN                   32760
#define ID_RMENU_FORCE                  32761
#define ID_RMENU_EXIT                   32762
#define ID_RMENU_NEWTICKET              32781
#define ID_RMENU_VIEWLOGS               32782
#define ID_GLPIAGENT_IDS                32783
#define ID_RMENU_SETTINGS               32784
#define IDC_STATIC                      -1
#define IDC_STATIC_TITLE                -1
#define IDC_GROUPBOX_NEWTICKETURL       -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
